/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "surface": "#131313",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#c6c6c7",
        "secondary-fixed": "#e5e2e1",
        "inverse-on-surface": "#303030",
        "on-surface": "#e4e2e1",
        "on-tertiary": "#2f3131",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#ffe088",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary": "#3c2f00",
        "on-secondary-container": "#bab8b7",
        "surface-container-low": "#1b1c1c",
        "primary-container": "#d4af37",
        "on-secondary-fixed-variant": "#474646",
        "on-primary-fixed": "#241a00",
        "inverse-primary": "#735c00",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#1a1c1c",
        "tertiary-container": "#b2b3b3",
        "on-primary-container": "#554300",
        "surface-bright": "#393939",
        "secondary-container": "#4a4949",
        "on-tertiary-container": "#434546",
        "on-tertiary-fixed-variant": "#454747",
        "on-surface-variant": "#d0c5af",
        "tertiary-fixed": "#e2e2e2",
        "on-background": "#e4e2e1",
        "outline-variant": "#4d4635",
        "surface-container-highest": "#353535",
        "primary-fixed-dim": "#e9c349",
        "surface-tint": "#e9c349",
        "secondary-fixed-dim": "#c9c6c5",
        "inverse-surface": "#e4e2e1",
        "secondary": "#c9c6c5",
        "primary": "#f2ca50",
        "on-primary-fixed-variant": "#574500",
        "on-secondary": "#313030",
        "surface-container": "#1f2020",
        "on-error-container": "#ffdad6",
        "outline": "#99907c",
        "background": "#131313",
        "surface-variant": "#353535",
        "tertiary": "#cecece"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "80px",
        "margin-mobile": "24px",
        "unit": "8px",
        "gutter": "32px",
        "section-gap": "160px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Bodoni Moda", "serif"],
        "display-lg": ["Bodoni Moda", "serif"],
        "headline-lg": ["Bodoni Moda", "serif"],
        "display-lg-mobile": ["Bodoni Moda", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Bodoni Moda", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        // Shorter aliases for easier use
        "serif": ["Bodoni Moda", "serif"],
        "sans": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "0.05em", fontWeight: "400" }],
        "display-lg": ["84px", { lineHeight: "92px", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "0.05em", fontWeight: "400" }],
        "display-lg-mobile": ["48px", { lineHeight: "52px", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "0.05em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "300" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.2em", fontWeight: "600" }],
      }
    },
  },
  plugins: [],
}